# Generated by Django 2.2.1 on 2019-05-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='images/')),
                ('time', models.DurationField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
